'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace KinetiqueServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="KinetiqueServiceReference.ISQLServer")>  _
    Public Interface ISQLServer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISQLServer/ExecuteNonQueryFromQueue", ReplyAction:="http://tempuri.org/ISQLServer/ExecuteNonQueryFromQueueResponse")>  _
        Function ExecuteNonQueryFromQueue(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long, ByVal QueueEntityID As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISQLServer/ExecuteNonQuery", ReplyAction:="http://tempuri.org/ISQLServer/ExecuteNonQueryResponse")>  _
        Function ExecuteNonQuery(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISQLServer/ExecuteNonQueryReturn", ReplyAction:="http://tempuri.org/ISQLServer/ExecuteNonQueryReturnResponse")>  _
        Function ExecuteNonQueryReturn(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISQLServer/ExecuteQuery", ReplyAction:="http://tempuri.org/ISQLServer/ExecuteQueryResponse")>  _
        Function ExecuteQuery(ByVal _strConnectionstring As String, ByVal _SQLSatement As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISQLServerChannel
        Inherits KinetiqueServiceReference.ISQLServer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SQLServerClient
        Inherits System.ServiceModel.ClientBase(Of KinetiqueServiceReference.ISQLServer)
        Implements KinetiqueServiceReference.ISQLServer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteNonQueryFromQueue(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long, ByVal QueueEntityID As Long) As Boolean Implements KinetiqueServiceReference.ISQLServer.ExecuteNonQueryFromQueue
            Return MyBase.Channel.ExecuteNonQueryFromQueue(Connectionstring, SQLStatement, IsCached, EntityID, QueueEntityID)
        End Function
        
        Public Function ExecuteNonQuery(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long) As Boolean Implements KinetiqueServiceReference.ISQLServer.ExecuteNonQuery
            Return MyBase.Channel.ExecuteNonQuery(Connectionstring, SQLStatement, IsCached, EntityID)
        End Function
        
        Public Function ExecuteNonQueryReturn(ByVal Connectionstring As String, ByVal SQLStatement As String, ByVal IsCached As Boolean, ByVal EntityID As Long) As System.Data.DataSet Implements KinetiqueServiceReference.ISQLServer.ExecuteNonQueryReturn
            Return MyBase.Channel.ExecuteNonQueryReturn(Connectionstring, SQLStatement, IsCached, EntityID)
        End Function
        
        Public Function ExecuteQuery(ByVal _strConnectionstring As String, ByVal _SQLSatement As String) As System.Data.DataSet Implements KinetiqueServiceReference.ISQLServer.ExecuteQuery
            Return MyBase.Channel.ExecuteQuery(_strConnectionstring, _SQLSatement)
        End Function
    End Class
End Namespace
